[package]
name = "discord-emoji"
version = "0.1.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[dependencies]
phf = "0.8.0"

[build-dependencies]
phf_codegen = "0.8.0"
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
