[package]
name = "discord-emoji"
version = "0.1.0"
authors = ["Noskcaj <kcajdev@gmail.com>"]
edition = "2018"

[dependencies]
phf = "0.10.1"

[build-dependencies]
phf_codegen = "0.10.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
